language: ruby
cache: bundler
install: bundle install
script: bundle exec jekyll build
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bundle exec s3_website push
notifications:
  email: false
