language: ruby
env:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true 
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
cache: bundler
install: bundle install
script: 
  - bundle exec jekyll build || travis_terminate 1
  - bundle exec htmlproofer --assume-extension --check-html --internal-domains nottoobadsoftware.com  ./_site || travis_terminate 1
 