version: 0.2

environment_variables:
  plaintext:
    LC_ALL: C.UTF-8
    ENV LANG: en_US.UTF-8
    ENV LANGUAGE: en_US.UTF-8

phases:
  install:
    runtime-versions:
      ruby: 2.6
      java: openjdk8
    commands:
      - bundle install
  build:
    commands:
      - JEKYLL_ENV=production bundle exec jekyll build
      - bundle exec htmlproofer --assume-extension --check-html --internal-domains nottoobadsoftware.com  ./_site
      - bundle exec s3_website push
