version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 2.5.0
    commands:
      - bundle install
  build:
    commands:
      - JEKYLL_ENV=production bundle exec jekyll build
      - bundle exec htmlproofer --assume-extension --check-html --internal-domains nottoobadsoftware.com  ./_site
artifacts:
  base-directory: '_site'
  files:
    - '**/*'
