version: 0.2

environment_variables:
  plaintext:
    LC_ALL: C.UTF-8
    ENV LANG: en_US.UTF-8
    ENV LANGUAGE: en_US.UTF-8
    JEKYLL_ENV: production

phases:
  install:
    runtime-versions:
      ruby: 2.6
      java: openjdk8
    commands:
      - bundle install
  build:
    commands:
      - ./_test.sh
      - bundle exec s3_website push
